### ISSUE TITLE
Error in weightMatrix[regulatorNames, ] <- weightMatrix.reg[regulatorNames,: number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by bharati-mehani** [aertslab/GENIE3#10]
Hi @s-aibar and All,
I am trying to run GENIE3 which is integrated with SCENIC, but it always get crashed with the given error:

```
Running GENIE3 part 1
Error in weightMatrix[regulatorNames, ] <- weightMatrix.reg[regulatorNames,  : 
  number of items to replace is not a multiple of replacement length
Calls: runGenie3 -> <Anonymous> -> <Anonymous> -> .GENIE3
In addition: Warning message:
In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled cores 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 20, 21, 24, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 43, 46, 47, 48, 49, 50, 51, 52, 53, 55, 56, 57, 59, 60 did not deliver results, all values of the jobs will be affected
Execution halted

```
I am running this on a dataset having 25721 genes from 25614 cells with 300GB memory. Kindly help me to resolve this issue. I have seen an earlier post #5 but could not solve this issue even by using 300GB memory. Any help will be highly appreciated.

Thanks

**Comment by ghuls** [comment]
Probably a lot of your processes crashed as it spawned too many of them for the amount of RAM you have.

Try with less cores (you had at least 60 of them), so you won't exhaust memory:
```
weightMatrix <- GENIE3(exprMatrix_filtered, regulators=inputTFs, nCores=20)
```

**Comment by WendyChen-github** [comment]
I also had this problem when I was running it. Can you tell me how you solved it? This problem has been bothering me for a long time.
