### ISSUE TITLE
unable to build a weight matrix on GENIE3

### ISSUE THREAD

**Issue by juugii** [aertslab/GENIE3#5]
Hello,

I have troubles in building a weightMatrix from GENIE3:

weightMatrix <- GENIE3(exprMatrix_filtered, regulators=inputTFs, nCores=36)
Error in weightMatrix[regulatorNames, ] <- weightMatrix.reg : 
the number of object to replace is not a multiple of the replacement size

I am following the guide from SCENIC from a scRNAseq matrix (about 12000x4000 starting matrix) step-by-step, with:

> dim(exprMatrix_filtered)
[1] 8467 3195
> length(inputTFs)
[1] 786
> table(inputTFs %in% rownames(exprMatrix_filtered))
TRUE 
 786 

What objects could have any wrong dimensions or properties ?
Thank you for your help,

Best regards.

Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu     

 GENIE3                            * 1.0.0    2018-04-18
 SCENIC                            * 0.1.7    2018-04-19
 AUCell                            * 0.99.5   2018-04-19
 RcisTarget.mm9.motifDatabases.20k * 0.1.1    2018-04-18

**Comment by orionzhou** [comment]
That error message typically occurs when there's not enough memory on the server - just try to request more memory (I'd go at least 200GB for that size of a matrix)

**Comment by hummuscience** [comment]
I have a similar problem, but I am limited with the amount of memory I have (60Gb).

I have a 13915x4391 matrix to run GENIE3 on. Is there a way to make it work with the 60Gb of memory that I have? I tried reducing the number of cores used. Started with 30 which gave that error, then I went down to 20 but eventually got the same error. 

Any ideas?
