### ISSUE TITLE
Allow custom foreach backend?

### ISSUE THREAD

**Issue by mschubert** [aertslab/GENIE3#8]
Would it be possible to adapt the [parallel processing code](https://github.com/aertslab/GENIE3/blob/master/R/GENIE3.R#L181) so that a user can supply their own `foreach` (or `BiocParallel`) backend?

This would [make it possible](http://bioconductor.org/packages/release/bioc/vignettes/BiocParallel/inst/doc/BiocParallel_BatchtoolsParam.pdf) to construct the weight matrix not only using multiple cores, but also multiple jobs on HPC.

**Comment by s-aibar** [comment]
Thank you for the suggestion 👍  I have integrated your pull request
